"""
Django settings for newsfinder project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Grab env vars for development or prod
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
ENVIRONMENT = os.environ.get('ENVIRONMENT', default='development')

# SECURITY WARNING: keep the secret key used in production secret!
# double dollar signs should be replaced with single if pasting back here as string
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', default='$-d7bl5kex1-*fwi@2e^sx=%q8zmty4bg&_5iv%#ftz1mht2x(')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = 1 means debug is turned on
DEBUG = int(os.environ.get('DJANGO_DEBUG', default=True))

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # local apps
    'pages.apps.PagesConfig',
    'users.apps.UsersConfig',
    'articles.apps.ArticlesConfig',
    'abtest.apps.AbtestConfig',
    # third-party
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newsfinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # enables environment variables to be passed to template context
                'newsfinder.context_processors.export_vars',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsfinder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db',
        'PORT': 5432  # default port for Postgres
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# django-crispy-forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Static files (CSS, JavaScript, Images) per app and shared
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'  # Must end in /
# Setting below points to 1 common static folder for all apps
STATICFILES_DIRS = (
    './static/',
)


# Custom users model (used in place of Django's default base user model)
# Model defined by users app
AUTH_USER_MODEL = 'users.CustomUser'


# Specify what happens on login and logout (where to redirect)
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


X_FRAME_OPTIONS = 'SAMEORIGIN'
